version: 2.11.0
apkFileName: com.google.android.googlequicksearchbox.apk
isFrameworkApk: false
usesFramework:
  ids:
  - 1
  tag: null
sdkInfo:
  minSdkVersion: 32
  targetSdkVersion: 36
packageInfo:
  forcedPackageId: 127
  renameManifestPackage: null
versionInfo:
  versionCode: 301708425
  versionName: 17.9.53.sa.arm64
sharedLibrary: false
sparseResources: true
compactEntries: false
doNotCompress:
- arsc
- dex
- mp3
- ogg
- png
- so
- wav
- webp
- META-INF/services/io.grpc.LoadBalancerProvider
- META-INF/services/io.grpc.NameResolverProvider
- assets/AltFormats_676
- assets/dexopt/baseline.prof
- assets/dexopt/baseline.profm
- assets/empty_asset_generated_by_bazel~
- assets/jspuffygame/fonts/Quicksand-Bold.woff2
- assets/phenotype/clienttracing_android_package_metadata.binarypb
- assets/phenotype/com_android_billingclient_package_metadata.binarypb
- assets/phenotype/com_google_android_gms_auth_account_client_package_metadata.binarypb
- assets/phenotype/com_google_android_gms_icing_mdd_package_metadata.binarypb
- assets/phenotype/com_google_android_gms_mdns_package_metadata.binarypb
- assets/phenotype/com_google_android_libraries_consent_flows_footprints_package_metadata.binarypb
- assets/phenotype/com_google_android_libraries_consentverifier_package_metadata.binarypb
- assets/phenotype/com_google_android_libraries_performance_primes_package_metadata.binarypb
- assets/phenotype/com_google_android_libraries_subscriptions_package_metadata.binarypb
- assets/phenotype/com_google_android_libraries_surveys_package_metadata.binarypb
- assets/phenotype/readaloud_package_metadata.binarypb
- assets/pop_nga_android_deployment_assets_symbols/R.aapt2.txt
- assets/pop_nga_android_deployment_symbols/R.aapt2.txt
- car-app-api.level
- org/joda/time/format/messages_en.properties
- org/joda/time/tz/data/Etc/GMT
- org/joda/time/tz/data/Etc/GMT+1
- org/joda/time/tz/data/Etc/GMT+10
- org/joda/time/tz/data/Etc/GMT+11
- org/joda/time/tz/data/Etc/GMT+12
- org/joda/time/tz/data/Etc/GMT+2
- org/joda/time/tz/data/Etc/GMT+3
- org/joda/time/tz/data/Etc/GMT+4
- org/joda/time/tz/data/Etc/GMT+5
- org/joda/time/tz/data/Etc/GMT+6
- org/joda/time/tz/data/Etc/GMT+7
- org/joda/time/tz/data/Etc/GMT+8
- org/joda/time/tz/data/Etc/GMT+9
- org/joda/time/tz/data/Etc/GMT-1
- org/joda/time/tz/data/Etc/GMT-10
- org/joda/time/tz/data/Etc/GMT-11
- org/joda/time/tz/data/Etc/GMT-12
- org/joda/time/tz/data/Etc/GMT-13
- org/joda/time/tz/data/Etc/GMT-14
- org/joda/time/tz/data/Etc/GMT-2
- org/joda/time/tz/data/Etc/GMT-3
- org/joda/time/tz/data/Etc/GMT-4
- org/joda/time/tz/data/Etc/GMT-5
- org/joda/time/tz/data/Etc/GMT-6
- org/joda/time/tz/data/Etc/GMT-7
- org/joda/time/tz/data/Etc/GMT-8
- org/joda/time/tz/data/Etc/GMT-9
- org/joda/time/tz/data/Etc/UTC
- res/drawable/assistant_ambient_logo_24dp
- res/raw/assistant_auto_tng_libraries_device_heterodyne_info
- res/raw/assistant_auto_tng_libraries_user_heterodyne_info
- res/raw/assistant_titan_device_heterodyne_info
- res/raw/assistant_titan_device_registration_info.binarypb
- res/raw/build_data.pb
- res/raw/clienttracing_android_heterodyne_info
- res/raw/clienttracing_android_registration_info.binarypb
- res/raw/com_android_billingclient_heterodyne_info
- res/raw/com_android_billingclient_registration_info.binarypb
- res/raw/com_google_android_apps_gsa_pcp_device_heterodyne_info
- res/raw/com_google_android_apps_gsa_pcp_user_heterodyne_info
- res/raw/com_google_android_apps_search_assistant_device_heterodyne_info
- res/raw/com_google_android_apps_search_assistant_mobile_device_heterodyne_info
- res/raw/com_google_android_apps_search_assistant_mobile_interactor_user_heterodyne_info
- res/raw/com_google_android_apps_search_assistant_platform_ondevice_fulfillment_server_pop_user_heterodyne_info
- res/raw/com_google_android_apps_search_assistant_user_heterodyne_info
- res/raw/com_google_android_apps_search_fedora_device_heterodyne_info
- res/raw/com_google_android_apps_search_omnient_device_heterodyne_info
- res/raw/com_google_android_apps_search_omnient_heterodyne_info
- res/raw/com_google_android_apps_search_policy_heterodyne_info
- res/raw/com_google_android_apps_search_readaloud_heterodyne_info
- res/raw/com_google_android_apps_search_smartsetup_heterodyne_info
- res/raw/com_google_android_apps_search_soundsearch_device_heterodyne_info
- res/raw/com_google_android_apps_search_transcription_device_heterodyne_info
- res/raw/com_google_android_gms_auth_account_client_heterodyne_info
- res/raw/com_google_android_gms_auth_account_client_registration_info.binarypb
- res/raw/com_google_android_gms_clearcut_client_heterodyne_info
- res/raw/com_google_android_gms_droidguardclient_heterodyne_info
- res/raw/com_google_android_gms_gcm_heterodyne_info
- res/raw/com_google_android_gms_gmscompliance_client_heterodyne_info
- res/raw/com_google_android_gms_gmscompliance_client_registration_info.binarypb
- res/raw/com_google_android_gms_gmscompliance_heterodyne_info
- res/raw/com_google_android_gms_icing_mdd_registration_info.binarypb
- res/raw/com_google_android_gms_mdns_heterodyne_info
- res/raw/com_google_android_gms_mdns_registration_info.binarypb
- res/raw/com_google_android_gms_ulr_heterodyne_info
- res/raw/com_google_android_gms_usagereporting_heterodyne_info
- res/raw/com_google_android_gms_usonia_heterodyne_info
- res/raw/com_google_android_gms_vision_heterodyne_info
- res/raw/com_google_android_libraries_consent_flows_footprints_registration_info.binarypb
- res/raw/com_google_android_libraries_consentverifier_heterodyne_info
- res/raw/com_google_android_libraries_consentverifier_registration_info.binarypb
- res/raw/com_google_android_libraries_mdi_sync_heterodyne_info
- res/raw/com_google_android_libraries_notifications_platform_heterodyne_info
- res/raw/com_google_android_libraries_onegoogle_consent_heterodyne_info
- res/raw/com_google_android_libraries_performance_primes_heterodyne_info
- res/raw/com_google_android_libraries_performance_primes_registration_info.binarypb
- res/raw/com_google_android_libraries_search_assistant_invocation_device_heterodyne_info
- res/raw/com_google_android_libraries_search_audio_device_heterodyne_info
- res/raw/com_google_android_libraries_search_searchbox_user_heterodyne_info
- res/raw/com_google_android_libraries_search_soda_apa_device_heterodyne_info
- res/raw/com_google_android_libraries_search_speech_tng_device_heterodyne_info
- res/raw/com_google_android_libraries_search_srp_library_user_heterodyne_info
- res/raw/com_google_android_libraries_search_user_heterodyne_info
- res/raw/com_google_android_libraries_search_voicesearch_heterodyne_info
- res/raw/com_google_android_libraries_subscriptions_registration_info.binarypb
- res/raw/com_google_android_libraries_surveys_registration_info.binarypb
- res/raw/com_google_ar_sceneviewer_android_device_heterodyne_info
- res/raw/com_google_ar_sceneviewer_android_user_heterodyne_info
- res/raw/device_goal_classifier_model.tflite_nocompress
- res/raw/googledata_experiments_mobile_assistant_client_packages_component_assistant_suw_user_heterodyne_info
- res/raw/googledata_experiments_mobile_assistant_client_packages_component_assistant_tng_interactor_device_heterodyne_info
- res/raw/googledata_experiments_mobile_assistant_client_packages_component_nlu_ff_device_heterodyne_info
- res/raw/googledata_experiments_mobile_assistant_client_packages_component_nlu_ff_user_heterodyne_info
- res/raw/googledata_experiments_mobile_assistant_client_packages_component_soda_hotword_device_heterodyne_info
- res/raw/googledata_experiments_mobile_assistant_client_packages_component_soda_resourcemanager_device_heterodyne_info
- res/raw/min_tested_nga_data_release_binarypb
- res/raw/readaloud_registration_info.binarypb
- res/raw/test_data_pb
- res/raw/tiktok_device_heterodyne_info
- res/raw/tiktok_directboot_heterodyne_info
